### ISSUE TITLE
warns on properties already being declared

### ISSUE THREAD

**Issue by JackChance** [JackChance/do_artifactory#2]
```
       * do_artifactory_gem[2.3.2] action install[2016-05-11T17:54:44+00:00] WARN: /tmp/kitchen/cache/cookbooks/do_artifactory/resources/gem.rb:8:in `block
```

(2 levels) in class_from_file': property version is declared in both chef_gem[artifactory] and do_artifactory_gem[2.3.2] action :install. Use new_resource.versi
on instead. At /tmp/kitchen/cache/cookbooks/do_artifactory/resources/gem.rb:8:in `block (2 levels) in class_from_file'
       [2016-05-11T17:54:44+00:00] WARN: /tmp/kitchen/cache/cookbooks/do_artifactory/resources/gem.rb:9:in`block (2 levels) in class_from_file': property sourc
e is declared in both chef_gem[artifactory] and do_artifactory_gem[2.3.2] action :install. Use new_resource.source instead. At /tmp/kitchen/cache/cookbooks/do_a
rtifactory/resources/gem.rb:9:in `block (2 levels) in class_from_file'

**Comment by JackChance** [comment]
Issues were with the gem resource, with it removed this issue no longer exists
